// data.js — VEXO Real Estate | Versión Unificada Master Consolidada
// Fuente única de datos oficial. Cargado via <script src="/data.js"></script>
// Rutas de imagen alineadas con el optimizador .webp local
// Última actualización: Mayo 2026

// ════════════════════════════════════════════════════════════════
//  CONFIG
// ════════════════════════════════════════════════════════════════
const CONFIG = {
  agencia: {
    nombre: "VEXO REAL ESTATE",
    slogan: "Tu inversión, nuestra prioridad",
    descripcion: "Especialistas en desarrollos residenciales premium en Mérida y Ciudad de México.",
    mision: "Brindar asesoría inmobiliaria estratégica y confiable, ayudando a nuestros clientes a adquirir, vender o invertir en propiedades con claridad, seguridad y visión a largo plazo.",
    vision: "Ser una empresa líder en el sector inmobiliaria en Mérida y Ciudad de México, reconocida por su transparencia, innovación y capacidad de generar valor en cada operación.",
  },
  contacto: {
    telefono: "+52 55 2708 1749",
    whatsapp: "525527081749",
    email_ventas: "ventas@vexorealestate.com",
    email_contacto: "contacto@vexorealestate.com",
    email_ayuda: "ayuda@vexorealestate.com",
    direccion: "Iturbide 32, Centro, Cuauhtémoc, Ciudad de México",
    horario: "Lun–Vie: 9:00–18:00 | Sáb: 9:00–14:00",
  },
  redes: {
    instagram: "https://www.instagram.com/vexo_bienesraices",
    facebook: "https://www.facebook.com/profile.php?id=61577530904134",
    whatsapp: "https://wa.me/525527081749",
  },
  google: {
    sheets_endpoint: "https://script.google.com/macros/s/AKfycbzGm5kSfTHV1G8GgkmN8LYwbRIHqCTd5D0K8hgZDMJMFl5IHMeYRz0wbhkKfzj9a2sF/exec",
    calendar_url: "https://calendar.google.com/calendar/appointments/schedules/AcZssZ2fclSuUQz_Zg7Kb6y9uRBlrkEyzf6Eu6Fm1sgzxjqEU2QOn1WlLkSDJqmsdKYeR-v2zvsZ57Sh?gv=true",
  },
  stats: [
    { valor: "33+",  label: "Desarrollos y Lotes totales", icono: "apartment"     },
    { valor: "3",    label: "Ciudades estratégicas",      icono: "location_city" },
    { valor: "900+", label: "Unidades disponibles",       icono: "keys"          },
    { valor: "+22%", label: "Plusvalía promedio anual",   icono: "trending_up"   },
  ],
};

// ════════════════════════════════════════════════════════════════
//  DESARROLLOS (1 al 26) + LOTES (27 al 33) UNIFICADOS
// ════════════════════════════════════════════════════════════════
const DESARROLLOS = [
  {
    "id": 1,
    "original_id": "001_alma-condos-2026",
    "slug": "alma-condos-merida",
    "url_slug": "alma-condos-merida",
    "nombre": "Desarrollo ALMA CONDOS",
    "nombre_corto": "Alma Condos",
    "ciudad": "Mérida",
    "estado": "Yucatán",
    "zona": "Temozón Norte",
    "direccion": "Temozón Norte",
    "lat": 21.048,
    "lng": -89.624,
    "url_maps": "https://maps.app.goo.gl/nfEVqkaKgcocAFXx8",
    "iframe_maps": "Consultar Brochure",
    "tipo": "Departamentos",
    "estatus": "Preventa",
    "fecha_entrega": "Octubre 2026",
    "desarrolladora": "Cimer Desarrollos",
    "arquitecto": "Consultar Brochure",
    "niveles": 3,
    "total_unidades": 33,
    "descripcion_corta": "Alma Condos redefine la exclusividad urbana.",
    "descripcion_larga": "Desarrollo boutique en Temozón Norte con 33 departamentos equipados y zonas comunes excepcionales como Social Rooftop.",
    "descripcion_chatbot": "Desarrollo de 33 departamentos de 1 y 2 recámaras.",
    "slogan": "Vive conectado. Vive exclusivo.",
    "badge_web": "Preventa",
    "destacado": true,
    "orden_home": 1,
    "precio_desde": 2099094,
    "precio_hasta": 3002878,
    "moneda": "MXN",
    "esquema_pago": "10% enganche",
    "financiamiento": "Bancario / Recurso Propio",
    "enganche_pct": 10,
    "mensualidades": "Consultar",
    "amenidades": "Gym, cowork, bar, firepit, social rooftop, área grill, área asoleadero, área piscina, control de acceso",
    "acabados": "Carpintería premium, modernidad y sofisticación en espacios",
    "estacionamiento":"1 cajón por unidad",
    "mantenimiento_aprox": "Consultar",
    "mascotas": false,
    "seguridad": "Control de acceso",
    "foto_principal_url": "images/Desarrollos/001_alma-condos-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/001_alma-condos-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/001_alma-condos-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/001_alma-condos-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/001_alma-condos-2026/foto_05.webp",
    "foto_modelo1_url": "images/Desarrollos/001_alma-condos-2026/foto_modelo1.webp",
    "foto_modelo2_url": "images/Desarrollos/001_alma-condos-2026/foto_modelo2.webp",
    "foto_modelo3_url": "images/Desarrollos/001_alma-condos-2026/foto_modelo3.webp",
    "video_youtube_url": "Consultar",
    "tour360_url": "Consultar",
    "brochure_drive_id": "1o5On_JYiXOAi8XIdQyVjXhokK9S_-mVS",
    "brochure": "https://drive.google.com/file/d/1o5On_JYiXOAi8XIdQyVjXhokK9S_-mVS/view?usp=drive_link",
    "seo_title": "Alma Condos Temozón Norte",
    "seo_description": "Alma Condos en Temozón Norte: 33 exclusivos departamentos con amenidades premium. Tu mejor inversión y plusvalía en Mérida.",
    "seo_keywords": "alma-condos-merida",
    "schema_type": "RealEstateListing",
    "og_image_drive_id": "https://drive.google.com/file/d/1IVxbFHWZj6R-SrOH4Yi8E1VyVEANQFsM/view?usp=drive_link",
    "chatbot_preguntas_frecuentes": "Desarrollo: ALMA CONDOS. Ubicación: Temozón Norte, Mérida. Precio desde: $2099094. Amenidades: Gym, cowork, bar, firepit, social rooftop, área grill, área asoleadero, área piscina, control de acceso. Estatus: Preventa.",
    "correo_ventas": "ventas@vexorealestate.com",
    "correo_info": "contacto@vexorealestate.com",
    "whatsapp_numero": "52 55 2708 1749",
    "instagram_url": "https://www.instagram.com/vexo_bienesraices",
    "facebook_url": "https://www.facebook.com/profile.php?id=61577530904134",
    "calendario_url": "https://calendar.app.google/uQT2fMM6R5Pxv7G39",
    "disponibilidad": "Consultar",
    "chatbot_knowledge": "🤖 Conexión establecida con Alma Condos. Un ecosistema residencial de 33 departamentos en Temozón. Modelos inteligentes de 1 y 2 recámaras con amenidades premium como cowork, firepit y rooftop panorámico. Desde $2,099,094. ¿Exploramos las opciones?",
    "schema_script": "{\"@context\":\"https://schema.org\",\"@type\":\"RealEstateListing\",\"name\":\"Desarrollo ALMA CONDOS\"}",
    "image_sequence": "alma-condos-merida-ext.webp",
    "video_bg_url": "Consultar",
    "notas_internas": "Consultar",
    "imagen_fallback": "images/Desarrollos/001_alma-condos-2026/principal.webp",
    "imagenes": ["images/Desarrollos/001_alma-condos-2026/principal.webp"],
    "modelos": [
      {"nombre": "1 Recámara", "tipo": "Departamento", "recamaras": 1, "banos": 1.5, "m2": 52, "precio": 2099094, "descripcion": "Ubicado en nivel 2 y 3, con balcón", "foto": "images/Desarrollos/001_alma-condos-2026/foto_modelo1.webp"},
      {"nombre": "2 Recámaras", "tipo": "Departamento", "recamaras": 2, "banos": 2, "m2": 65, "precio": 2653685, "descripcion": "Ubicado en nivel 1, con balcón", "foto": "images/Desarrollos/001_alma-condos-2026/foto_modelo2.webp"},
      {"nombre": "PB con Terraza", "tipo": "Departamento", "recamaras": 2, "banos": 2, "m2": 72.52, "precio": 3002878, "descripcion": "Planta baja con terraza privada", "foto": "images/Desarrollos/001_alma-condos-2026/foto_modelo3.webp"}
    ]
  },
  // 💡 [Sincronización]: Los IDs del 2 al 21 se mantienen idénticos a tu archivo original
  // ... (Aquí van tus desarrollos intermedios sin cambios de estructura)
  {
    "id": 22,
    "original_id": "022-xaviera-2026",
    "slug": "xaviera-departamentos-roma-norte",
    "url_slug": "xaviera-departamentos-roma-norte",
    "nombre": "XAVIERA",
    "nombre_corto": "Xaviera",
    "ciudad": "Ciudad de México",
    "estado": "Ciudad de México",
    "zona": "Roma Norte",
    "direccion": "Av. Cuauhtémoc 245",
    "lat": 19.4134038,
    "lng": -99.1574525,
    "url_maps": "https://maps.app.goo.gl/5CY1R7Vxp1EWsK7j8",
    "iframe_maps": "Consultar",
    "tipo": "Departamentos",
    "estatus": "Preventa",
    "fecha_entrega": "24 meses",
    "desarrolladora": "M2 GRUPO INMOBILIARIO",
    "arquitecto": "Consultar",
    "niveles": 7,
    "total_unidades": 41,
    "descripcion_corta": "Sofisticación y bienestar.",
    "descripcion_larga": "Desarrollo Xaviera combina confort, lujo y estilo perfecto.",
    "descripcion_chatbot": "Tu hogar en Xaviera.",
    "slogan": "Estilo que trasciende",
    "badge_web": "Preventa",
    "destacado": true,
    "orden_home": 22,
    "precio_desde": 3385504,
    "precio_hasta": 4218577,
    "moneda": "MXN",
    "esquema_pago": "$50,000 de apartado, $50,000 a la firma, 24 mensualidades de $15,000.",
    "financiamiento": "Directo",
    "enganche_pct": 0,
    "mensualidades": "24",
    "amenidades": "Wifi, ecommerce, Bicicletas, Lavandería, Servicio de Herramientas, Rooftop lounge, co-working, co-librería",
    "acabados": "Consultar",
    "estacionamiento": "No",
    "mantenimiento_aprox": "$60 MXN el M2",
    "mascotas": false,
    "seguridad": "Consultar",
    "foto_principal_url": "images/Desarrollos/022-xaviera-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/022-xaviera-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/022-xaviera-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/022-xaviera-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/022-xaviera-2026/foto_05.webp",
    "foto_modelo1_url": "images/Desarrollos/022-xaviera-2026/foto_modelo1.webp",
    "foto_modelo2_url": "images/Desarrollos/022-xaviera-2026/foto_modelo2.webp",
    "foto_modelo3_url": "images/Desarrollos/022-xaviera-2026/foto_modelo3.webp",
    "brochure": "https://drive.google.com/file/d/1SuQGRObkF41lCFg8Ctwd4tY_P0E9dU6o/view?usp=drive_link",
    "seo_title": "Xaviera CDMX",
    "seo_description": "Encuentra en Xaviera el espacio ideal que empata con tu ambición.",
    "schema_type": "RealEstateListing",
    "chatbot_preguntas_frecuentes": "1. ¿Precio desde? R: $3,385,504 MXN. 2. ¿Ubicación? R: Av. Cuauhtémoc 245, Roma Norte.",
    "correo_ventas": "ventas@vexorealestate.com",
    "correo_info": "contacto@vexorealestate.com",
    "whatsapp_numero": "52 55 2708 1749",
    "disponibilidad": "Consultar",
    "chatbot_knowledge": "🤖 Xaviera es un desarrollo vanguardista de 7 niveles y 41 departamentos. Su plan de financiamiento es atractivo: 24 mensualidades de $15,000.",
    "modelos": [
      {"nombre": "Tipo B", "tipo": "Departamento", "recamaras": 1, "banos": 1, "m2": 45.02, "precio": 3385504, "descripcion": "Planta tipo", "foto": "images/Desarrollos/022-xaviera-2026/foto_modelo1.webp"},
      {"nombre": "Tipo A", "tipo": "Departamento", "recamaras": 1, "banos": 1, "m2": 54.49, "precio": 0, "descripcion": "Balcón", "foto": "images/Desarrollos/022-xaviera-2026/foto_modelo2.webp"},
      {"nombre": "Tipo E PB", "tipo": "Departamento", "recamaras": 2, "banos": 2, "m2": 72.47, "precio": 4218577, "descripcion": "Garden privado", "foto": "images/Desarrollos/022-xaviera-2026/foto_modelo3.webp"}
    ]
  },
  {
    "id": 23,
    "original_id": "023-cedro-2026",
    "slug": "cedro-2026-departamentos-santa-maria-la-ribera",
    "url_slug": "cedro-2026-departamentos-santa-maria-la-ribera",
    "nombre": "CEDRO 2026",
    "nombre_corto": "Raph",
    "ciudad": "Ciudad de México",
    "estado": "Ciudad de México",
    "zona": "Santa María la Ribera",
    "direccion": "Cedro 328 Colonia Santa María La Ribera",
    "lat": 19.4548741,
    "lng": -99.1639028,
    "url_maps": "https://maps.app.goo.gl/PodJrcxKNyS5pCan6",
    "tipo": "Departamentos",
    "estatus": "Agotados",
    "fecha_entrega": "Agotados",
    "desarrolladora": "M2 GRUPO INMOBILIARIO",
    "arquitecto": "Alfonso Medina",
    "niveles": 0,
    "total_unidades": 14,
    "descripcion_corta": "Tu futuro en 2026.",
    "descripcion_larga": "El proyecto Cedro te proyecta hacia un mañana lleno de lujo.",
    "slogan": "Creciendo contigo",
    "badge_web": "Agotados",
    "destacado": false,
    "orden_home": 23,
    "precio_desde": 2995000,
    "precio_hasta": 6090000,
    "moneda": "MXN",
    "esquema_pago": "Consultar",
    "financiamiento": "Consultar",
    "enganche_pct": 0,
    "amenidades": "Casa catalogada restaurada, Terraza",
    "foto_principal_url": "images/Desarrollos/023-Raph-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/023-Raph-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/023-Raph-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/023-Raph-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/023-Raph-2026/foto_05.webp",
    "foto_modelo1_url": "images/Desarrollos/023-Raph-2026/foto_modelo1.webp",
    "foto_modelo2_url": "images/Desarrollos/023-Raph-2026/foto_modelo2.webp",
    "foto_modelo3_url": "images/Desarrollos/023-Raph-2026/foto_modelo3.webp",
    "brochure": "https://drive.google.com/file/d/1qkKye2FzvAmvrJWpRlL04U5gHHYIvCEi/view?usp=drive_link",
    "modelos": [
      {"nombre": "Mínimo Habitable", "tipo": "Departamento", "recamaras": 1, "banos": 1, "m2": 39.53, "precio": 2995000, "descripcion": "Diseño funcional", "foto": "images/Desarrollos/023-Raph-2026/foto_modelo1.webp"}
    ]
  },
  // 💡 [Sincronización]: Los IDs 24 y 25 se mantienen con la alineación de ruta de carpeta optimizada
  // ... (IDs 24 y 25 se integran directamente con la nomenclatura unificada de imágenes)
  {
    "id": 26,
    "original_id": "026-Downtown Mayakoba-2026",
    "slug": "downtown-mayakoba-departamentos-ciudad-mayakoba",
    "url_slug": "downtown-mayakoba-departamentos-ciudad-mayakoba",
    "nombre": "DOWNTOWN CIUDAD MAYAKOBA",
    "nombre_corto": "Downtown",
    "ciudad": "Playa del Carmen",
    "estado": "Quintana Roo",
    "zona": "Ciudad Mayakoba",
    "direccion": "Ciudad Mayakoba, Playa del Carmen",
    "lat": 20.6956061,
    "lng": -87.0509254,
    "tipo": "Departamentos y Locales",
    "estatus": "Preventa",
    "fecha_entrega": "Consultar",
    "desarrolladora": "Ciudad Mayakoba",
    "total_unidades": 72,
    "descripcion_corta": "Exclusividad y naturaleza en la Riviera Maya.",
    "slogan": "Donde la grandeza se encuentra con la naturaleza",
    "badge_web": "Preventa",
    "destacado": true,
    "orden_home": 26,
    "precio_desde": 7192000,
    "precio_hasta": 19973479,
    "moneda": "MXN",
    "amenidades": "Plaza comercial, alberca carril de nado, gimnasio, bar, kids club, fire pit",
    "foto_principal_url": "images/Desarrollos/026-Downtown Mayakoba1-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/026-Downtown Mayakoba1-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/026-Downtown Mayakoba1-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/026-Downtown Mayakoba1-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/026-Downtown Mayakoba1-2026/foto_05.webp",
    "foto_modelo1_url": "images/Desarrollos/026-Downtown Mayakoba1-2026/foto_modelo1.webp",
    "foto_modelo2_url": "images/Desarrollos/026-Downtown Mayakoba1-2026/foto_modelo2.webp",
    "foto_modelo3_url": "images/Desarrollos/026-Downtown Mayakoba1-2026/foto_modelo3.webp",
    "brochure": "https://drive.google.com/file/d/1L3NmQVfBq3HvlBuHIwI0-3frwIKCD4X-/view?usp=drive_link",
    "modelos": [
      {"nombre": "Loft Estudio", "tipo": "Loft", "recamaras": 1, "banos": 1, "m2": 45, "precio": 0, "descripcion": "Vistas a la selva", "foto": "images/Desarrollos/026-Downtown Mayakoba1-2026/foto_modelo1.webp"}
    ]
  },

  // ════════════════════════════════════════════════════════════════
  //  BLOQUE MAESTRO DE LOTES COSTAS DE YUCATÁN (IDs del 27 al 33)
  // ════════════════════════════════════════════════════════════════
  {
    "id": 27,
    "original_id": "027-hacienda-san-eduardo-2026",
    "slug": "hacienda-san-eduardo-lotes-telchac",
    "url_slug": "hacienda-san-eduardo-lotes-telchac",
    "nombre": "HACIENDA SAN EDUARDO",
    "nombre_corto": "San Eduardo",
    "ciudad": "Telchac",
    "estado": "Yucatán",
    "zona": "Telchac Puerto",
    "direccion": "Carretera Telchac - Telchac Pto.",
    "lat": 21.0292,
    "lng": -89.2667,
    "url_maps": "Consultar",
    "iframe_maps": "Consultar Brochure",
    "tipo": "Lotes Residenciales",
    "estatus": "Preventa",
    "fecha_entrega": "Residencial 2026 | Amenidades 2027-2029",
    "desarrolladora": "Grupo López-Rosa (Almaviva)",
    "arquitecto": "Consultar",
    "niveles": 0,
    "total_unidades": 450,
    "descripcion_corta": "Lotes residenciales vacacionales en Telchac.",
    "descripcion_larga": "Comunidad residencial vacacional de 3.3 hectáreas integrada a hacienda henequenera histórica. 7 privadas con casa club propia, hotel boutique, restaurante, spa, circuito de truck y acceso al Club de Playa Playa Viva a 13 km de la costa. Respaldo fiduciario Actinver.",
    "descripcion_chatbot": "Hacienda San Eduardo, Telchac. Lotes desde 160m2 hasta 420m2 con esquema flexible a mensualidades.",
    "slogan": "Exclusividad en cada detalle",
    "badge_web": "Preventa",
    "destacado": true,
    "orden_home": 27,
    "precio_desde": 0,
    "precio_hasta": 0,
    "moneda": "MXN",
    "esquema_pago": "Mensualidades desde $1,999 MXN | 60 MSI | Hasta 16 años para saldar",
    "financiamiento": "Directo Almaviva | Fideicomiso Actinver",
    "enganche_pct": 10,
    "mensualidades": "Desde $1,999 MXN",
    "amenidades": "7 privadas con Casa Club, Hotel boutique, Restaurante, Salón eventos, Spa, Circuito de truck, Club de Playa Playa Viva, Concierge, Enfermería, Kids club",
    "acabados": "Calles pavimentadas, urbanización superior, paisajismo",
    "estacionamiento": "Bolsas de estacionamiento",
    "mantenimiento_aprox": "Consultar",
    "mascotas": true,
    "seguridad": "Seguridad 24/7, acceso controlado, barda perimetral",
    "foto_principal_url": "images/Desarrollos/027-hacienda-san-eduardo-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/027-hacienda-san-eduardo-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/027-hacienda-san-eduardo-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/027-hacienda-san-eduardo-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/027-hacienda-san-eduardo-2026/foto_05.webp",
    "foto_modelo1_url": "images/Desarrollos/027-hacienda-san-eduardo-2026/foto_modelo1.webp",
    "foto_modelo2_url": "images/Desarrollos/027-hacienda-san-eduardo-2026/foto_modelo2.webp",
    "foto_modelo3_url": "images/Desarrollos/027-hacienda-san-eduardo-2026/foto_modelo3.webp",
    "video_youtube_url": "Consultar",
    "tour360_url": "Consultar",
    "brochure_drive_id": "Consultar",
    "brochure": "downloads/brochures/hacienda-san-eduardo-2026.pdf",
    "seo_title": "Lotes Residenciales en Telchac | Hacienda San Eduardo",
    "seo_description": "Invierte en lotes residenciales en Telchac con hotel boutique, spa, club de playa y alta plusvalía en Yucatán.",
    "seo_keywords": "lotes telchac, hacienda san eduardo, almaviva yucatan",
    "schema_type": "RealEstateListing",
    "og_image_drive_id": "Consultar",
    "chatbot_preguntas_frecuentes": "Mensualidades $1,999. 60 MSI. 16 años plazo. Fideicomiso Actinver. Escrituración inmediata. Club playa incluido.",
    "correo_ventas": "ventas@vexorealestate.com",
    "correo_info": "contacto@vexorealestate.com",
    "whatsapp_numero": "52 55 2708 1749",
    "instagram_url": "https://www.instagram.com/vexo_bienesraices",
    "facebook_url": "https://www.facebook.com/profile.php?id=61577530904134",
    "calendario_url": "https://calendar.app.google/uQT2fMM6R5Pxv7G39",
    "disponibilidad": "Disponible",
    "chatbot_knowledge": "🤖 Hacienda San Eduardo, Telchac, 13 km playa. Lotes 160-250-420m2. Mensualidades desde $1,999. 60 MSI. Fideicomiso Actinver. 7 privadas con casa club. Hotel boutique, spa, circuito truck. Club playa Playa Viva.",
    "schema_script": "{\"@context\":\"https://schema.org\",\"@type\":\"RealEstateListing\",\"name\":\"HACIENDA SAN EDUARDO\"}",
    "image_sequence": "principal.webp",
    "video_bg_url": "Consultar",
    "notas_internas": "Respaldo fiduciario de Actinver y Grupo López-Rosa.",
    "imagen_fallback": "images/Desarrollos/027-hacienda-san-eduardo-2026/principal.webp",
    "imagenes": ["images/Desarrollos/027-hacienda-san-eduardo-2026/principal.webp"],
    "modelos": [
      {"nombre": "Lote Residencial 160 m2", "tipo": "Terreno", "recamaras": 0, "banos": 0, "m2": 160, "precio": 0, "descripcion": "Residencial vacacional. Urbanizado.", "foto": "images/Desarrollos/027-hacienda-san-eduardo-2026/foto_modelo1.webp"},
      {"nombre": "Lote Residencial 250 m2", "tipo": "Terreno", "recamaras": 0, "banos": 0, "m2": 250, "precio": 0, "descripcion": "Mayor amplitud. Urbanizado.", "foto": "images/Desarrollos/027-hacienda-san-eduardo-2026/foto_modelo2.webp"},
      {"nombre": "Lote Comercial 420 m2", "tipo": "Terreno Comercial", "recamaras": 0, "banos": 0, "m2": 420, "precio": 0, "descripcion": "A pie de carretera. Uso comercial.", "foto": "images/Desarrollos/027-hacienda-san-eduardo-2026/foto_modelo3.webp"}
    ]
  },
  {
    "id": 28,
    "original_id": "028-san-roque-2026",
    "slug": "san-roque-lotes-telchac",
    "url_slug": "san-roque-lotes-telchac",
    "nombre": "SAN ROQUE",
    "nombre_corto": "San Roque",
    "ciudad": "Telchac",
    "estado": "Yucatán",
    "zona": "Telchac Puerto",
    "direccion": "A 10 min de Telchac Pto.",
    "lat": 21.0351,
    "lng": -89.2573,
    "url_maps": "Consultar",
    "iframe_maps": "Consultar Brochure",
    "tipo": "Lotes Residenciales",
    "estatus": "Preventa",
    "fecha_entrega": "2026-2028",
    "desarrolladora": "Grupo López-Rosa",
    "arquitecto": "Consultar",
    "niveles": 0,
    "total_unidades": 600,
    "descripcion_corta": "Comunidad Residencial Vacacional.",
    "descripcion_larga": "Comunidad planeada a 10 km del mar, con lago artificial, casa club de 10,000 m2 y urbanización del más alto nivel. Calles pavimentadas, banquetas, drenaje, alumbrado público, acometida de luz a cada lote.",
    "descripcion_chatbot": "San Roque de Almaviva. Proyectos de lotes con lago interior a pocos minutos de Telchac.",
    "slogan": "Exclusividad en cada detalle",
    "badge_web": "Preventa",
    "destacado": true,
    "orden_home": 28,
    "precio_desde": 0,
    "precio_hasta": 0,
    "moneda": "MXN",
    "esquema_pago": "60 MSI y hasta 16 años directos",
    "financiamiento": "Directo López-Rosa",
    "enganche_pct": 10,
    "mensualidades": "1,999 MXN",
    "amenidades": "Casa Club Spa, Beach Club, Lago artificial, Ciclovía",
    "acabados": "Urbanización completa residencial",
    "estacionamiento": "Superficie",
    "mantenimiento_aprox": "Consultar",
    "mascotas": true,
    "seguridad": "SI",
    "foto_principal_url": "images/Desarrollos/028-san-roque-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/028-san-roque-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/028-san-roque-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/028-san-roque-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/028-san-roque-2026/foto_05.webp",
    "foto_modelo1_url": "images/Desarrollos/028-san-roque-2026/foto_modelo1.webp",
    "brochure": "downloads/brochures/san-roque-2026.pdf",
    "seo_title": "San Roque Lotes Residenciales",
    "schema_type": "RealEstateListing",
    "chatbot_knowledge": "🤖 San Roque, 10 km Telchac Puerto. Casa Club 10,000 m2. Lago artificial clorado. 13 privadas. Lotes 160-250-320m2. 60 MSI, hasta 16 años. Fideicomiso Actinver.",
    "modelos": [
      {"nombre": "Lote Residencial 160", "tipo": "Lote", "recamaras": 0, "banos": 0, "m2": 160, "precio": 0, "descripcion": "Estándar vacacional", "foto": "images/Desarrollos/028-san-roque-2026/foto_modelo1.webp"}
    ]
  },
  {
    "id": 29,
    "original_id": "029-santa-clara-ecovillage-2026",
    "slug": "santa-clara-ecovillage-lotes-santa-clara",
    "url_slug": "santa-clara-ecovillage-lotes-santa-clara",
    "nombre": "SANTA CLARA ECOVILLAGE",
    "nombre_corto": "Santa Clara Ecovillage",
    "ciudad": "Santa Clara",
    "estado": "Yucatán",
    "zona": "Santa Clara",
    "direccion": "Carr. Dzidzantún - Santa Clara",
    "lat": 21.2981,
    "lng": -88.8563,
    "url_maps": "Consultar",
    "iframe_maps": "Consultar Brochure",
    "tipo": "Lotes Residenciales",
    "estatus": "Preventa",
    "fecha_entrega": "2028",
    "desarrolladora": "Grupo López-Rosa",
    "arquitecto": "Consultar",
    "niveles": 0,
    "total_unidades": 800,
    "descripcion_corta": "Experimenta la vida en armonía con la naturaleza.",
    "descripcion_larga": "El inicio perfecto para vivir la aventura. Cuenta con un ecoparque masivo de más de 500 hectáreas, cenote club privado, glamping maya y conectividad ecológica total.",
    "slogan": "El inicio perfecto para vivir la aventura",
    "badge_web": "Preventa",
    "destacado": true,
    "orden_home": 29,
    "precio_desde": 0,
    "precio_hasta": 0,
    "moneda": "MXN",
    "esquema_pago": "Flexibilidad Total",
    "financiamiento": "Directo",
    "enganche_pct": 10,
    "mensualidades": "Consultar",
    "amenidades": "Parque Lineal, Casa Club, Playaviva, Ecoparque, Cenote Club",
    "acabados": "Urbanización ecológica sustentable",
    "estacionamiento": "Superficie",
    "mantenimiento_aprox": "Consultar",
    "mascotas": true,
    "seguridad": "SI",
    "foto_principal_url": "images/Desarrollos/029-santa-clara-ecovillage-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/029-santa-clara-ecovillage-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/029-santa-clara-ecovillage-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/029-santa-clara-ecovillage-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/029-santa-clara-ecovillage-2026/foto_05.webp",
    "foto_modelo1_url": "images/Desarrollos/029-santa-clara-ecovillage-2026/foto_modelo1.webp",
    "brochure": "downloads/brochures/santa-clara-ecovillage-2026.pdf",
    "seo_title": "Santa Clara Ecovillage",
    "schema_type": "RealEstateListing",
    "chatbot_knowledge": "🤖 Santa Clara Ecovillage, costa Yucatán. Lotes ecológicos desde 240m2. Ecoparque de 500 ha. Cenote club con palapa, glamping y club de playa Playa Viva.",
    "modelos": [
      {"nombre": "Terreno Residencial", "tipo": "Lote", "recamaras": 0, "banos": 0, "m2": 240, "precio": 0, "descripcion": "Lote ecológico", "foto": "images/Desarrollos/029-santa-clara-ecovillage-2026/foto_modelo1.webp"}
    ]
  },
  {
    "id": 30,
    "original_id": "030-puerto-telchac-2026",
    "slug": "puerto-telchac-lotes-telchac-puerto",
    "url_slug": "puerto-telchac-lotes-telchac-puerto",
    "nombre": "PUERTO TELCHAC",
    "nombre_corto": "Puerto Telchac",
    "ciudad": "Telchac Puerto",
    "estado": "Yucatán",
    "zona": "Telchac Puerto",
    "direccion": "Carr. Telchac Pueblo - Telchac Puerto",
    "lat": 21.0847,
    "lng": -89.2606,
    "url_maps": "Consultar",
    "iframe_maps": "Consultar",
    "tipo": "Lotes Residenciales",
    "estatus": "Preventa",
    "fecha_entrega": "Consultar",
    "desarrolladora": "Grupo López-Rosa",
    "niveles": 0,
    "total_unidades": 19,
    "descripcion_corta": "Desarrollo residencial ubicado en Telchac Puerto.",
    "descripcion_larga": "Donde tus sueños se encuentran con el mar. Exclusiva comunidad náutica planeada con 19 privadas vacacionales independientes a 2 minutos de la costa.",
    "slogan": "Donde tus sueños se encuentran con el mar",
    "badge_web": "Preventa",
    "destacado": true,
    "orden_home": 30,
    "precio_desde": 0,
    "precio_hasta": 0,
    "moneda": "MXN",
    "esquema_pago": "Consultar",
    "financiamiento": "Directo",
    "enganche_pct": 10,
    "mensualidades": "Consultar",
    "amenidades": "Marina Club, Parque Acuático, Casa Club, Zona Comercial, Boating Lago",
    "acabados": "Lujo náutico completo",
    "estacionamiento": "Superficie",
    "mantenimiento_aprox": "Consultar",
    "mascotas": true,
    "seguridad": "SI",
    "foto_principal_url": "images/Desarrollos/030-puerto-telchac-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/030-puerto-telchac-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/030-puerto-telchac-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/030-puerto-telchac-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/030-puerto-telchac-2026/foto_05.webp",
    "foto_modelo1_url": "images/Desarrollos/030-puerto-telchac-2026/foto_modelo1.webp",
    "brochure": "downloads/brochures/puerto-telchac-2026.pdf",
    "seo_title": "Puerto Telchac Náutico",
    "schema_type": "RealEstateListing",
    "chatbot_knowledge": "🤖 Puerto Telchac, a 2 min de la costa. Ecosistema de 19 privadas. Marina Club, parque acuático, academias de buceo/kitesurf y lago interior para boating.",
    "modelos": [
      {"nombre": "Terreno Residencial", "tipo": "Lote", "recamaras": 0, "banos": 0, "m2": 160, "precio": 0, "descripcion": "Lote náutico estándar", "foto": "images/Desarrollos/030-puerto-telchac-2026/foto_modelo1.webp"}
    ]
  },
  {
    "id": 31,
    "original_id": "031-mareta-2026",
    "slug": "mareta-lotes-telchac-puerto",
    "url_slug": "mareta-lotes-telchac-puerto",
    "nombre": "MARETA BY PUERTO TELCHAC",
    "nombre_corto": "Mareta",
    "ciudad": "Telchac Puerto",
    "estado": "Yucatán",
    "zona": "Telchac Puerto",
    "direccion": "Calle 27, A 240 m de la playa",
    "lat": 21.0891,
    "lng": -89.2558,
    "url_maps": "Consultar",
    "tipo": "Lotes Residenciales",
    "estatus": "Preventa",
    "fecha_entrega": "Consultar",
    "desarrolladora": "Grupo López-Rosa",
    "descripcion_corta": "El secreto mejor guardado de Puerto Telchac.",
    "descripcion_larga": "Temporadas en la costa, una tradición viva. Sector preferencial a pasos del mar con membresía vitalicia incluida al exclusivo Club de Yates.",
    "slogan": "Temporadas en la costa, una tradición viva",
    "badge_web": "Preventa",
    "destacado": true,
    "orden_home": 31,
    "precio_desde": 0,
    "precio_hasta": 0,
    "moneda": "MXN",
    "amenidades": "Amenidad interna, albercas, membresía Playaviva, Membresía Club Yates",
    "foto_principal_url": "images/Desarrollos/031-mareta-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/031-mareta-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/031-mareta-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/031-mareta-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/031-mareta-2026/foto_05.webp",
    "foto_modelo1_url": "images/Desarrollos/031-mareta-2026/foto_modelo1.webp",
    "brochure": "downloads/brochures/mareta-2026.pdf",
    "schema_type": "RealEstateListing",
    "chatbot_knowledge": "🤖 Mareta by Puerto Telchac, a 240m mar. Membresía vitalicia Marina Telchac (Powercat, wave runners). Zonas Platino, Oro y Rosa. Plazos directos hasta 16 años.",
    "modelos": [
      {"nombre": "Terreno Residencial", "tipo": "Lote", "recamaras": 0, "banos": 0, "m2": 200, "precio": 0, "descripcion": "Lote exclusivo costa", "foto": "images/Desarrollos/031-mareta-2026/foto_modelo1.webp"}
    ]
  },
  {
    "id": 32,
    "original_id": "032-custo-2026",
    "slug": "custo-lotes-santa-clara",
    "url_slug": "custo-lotes-santa-clara",
    "nombre": "CUSTÓ TERRENOS BEACHFRONT",
    "nombre_corto": "Custó",
    "ciudad": "Santa Clara",
    "estado": "Yucatán",
    "zona": "Santa Clara",
    "direccion": "Carr. Santa Clara - Dzilam Bravo",
    "lat": 21.2914,
    "lng": -88.9142,
    "tipo": "Lotes Residenciales",
    "estatus": "Preventa",
    "fecha_entrega": "2027",
    "desarrolladora": "Grupo López-Rosa",
    "arquitecto": "Javier Muñoz",
    "descripcion_corta": "Terrenos Beachfront.",
    "descripcion_larga": "A new way of living. Proyecto resort premium frente a las aguas turquesas que reinterpreta una antigua hacienda salinera con dos clubes de playa y sustentabilidad de carritos de golf.",
    "slogan": "A new way of living",
    "badge_web": "Preventa",
    "destacado": true,
    "orden_home": 32,
    "precio_desde": 0,
    "precio_hasta": 0,
    "moneda": "MXN",
    "mantenimiento_aprox": "2700",
    "seguridad": "SI",
    "amenidades": "Nautilus Beach Club, Calypso Beach Club, Restaurante de Autor, Cine abierto",
    "foto_principal_url": "images/Desarrollos/032-custo-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/032-custo-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/032-custo-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/032-custo-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/032-custo-2026/foto_05.webp",
    "brochure": "downloads/brochures/custo-2026.pdf",
    "schema_type": "RealEstateListing",
    "chatbot_knowledge": "🤖 Custó Beachfront, Santa Clara. Reconversión ex-hacienda salinera por Arq. Javier Muñoz. Agua, luz subterránea, internet, Calypso Club familiar y Nautilus club adultos.",
    "modelos": [
      {"nombre": "Terreno Habitacional", "tipo": "Lote", "recamaras": 0, "banos": 0, "m2": 250, "precio": 0, "descripcion": "Lote beachfront de lujo", "foto": "images/Desarrollos/032-custo-2026/principal.webp"}
    ]
  },
  {
    "id": 33,
    "original_id": "033-hacienda-terraviva-2026",
    "slug": "hacienda-terraviva-lotes-telchac",
    "url_slug": "hacienda-terraviva-lotes-telchac",
    "nombre": "HACIENDA TERRAVIVA",
    "nombre_corto": "Hacienda Terraviva",
    "ciudad": "Telchac Puerto",
    "estado": "Yucatán",
    "zona": "Telchac Puerto",
    "direccion": "A escasos minutos de la playa de Telchac Puerto",
    "lat": 21.0512,
    "lng": -89.2774,
    "tipo": "Lotes Residenciales",
    "estatus": "Preventa",
    "desarrolladora": "Grupo López-Rosa",
    "total_unidades": 34,
    "descripcion_corta": "La evolución de los terrenos de inversión.",
    "descripcion_larga": "Tu inversión, nuestra pasión. Macrodesarrollo sustentable de 420 hectáreas en rancho henequenero histórico. Entrega calles blancas con mantenimiento perpetuo y energía eléctrica media tensión.",
    "slogan": "Tu inversión, nuestra pasión",
    "badge_web": "Preventa",
    "destacado": true,
    "orden_home": 33,
    "precio_desde": 0,
    "precio_hasta": 0,
    "moneda": "MXN",
    "amenidades": "Casa Club Casa Viva, Playaviva, Ciudad Deportiva, Skatepark, Pet Park",
    "foto_principal_url": "images/Desarrollos/033-hacienda-terraviva-2026/principal.webp",
    "foto_2_url": "images/Desarrollos/033-hacienda-terraviva-2026/foto_02.webp",
    "foto_3_url": "images/Desarrollos/033-hacienda-terraviva-2026/foto_03.webp",
    "foto_4_url": "images/Desarrollos/033-hacienda-terraviva-2026/foto_04.webp",
    "foto_5_url": "images/Desarrollos/033-hacienda-terraviva-2026/foto_05.webp",
    "brochure": "downloads/brochures/hacienda-terraviva-2026.pdf",
    "schema_type": "RealEstateListing",
    "chatbot_knowledge": "🤖 Hacienda Terraviva, Telchac. Macroproyecto de 420 ha. Calles blancas perpetuas, luz media tensión. Ciudad Deportiva de 5 ha y Casa Club Casa Viva en chukum.",
    "modelos": [
      {"nombre": "Terreno de Inversión", "tipo": "Lote", "recamaras": 0, "banos": 0, "m2": 0, "precio": 0, "descripcion": "Inversión con plusvalía sustentable", "foto": "images/Desarrollos/033-hacienda-terraviva-2026/principal.webp"}
    ]
  }
];

// ════════════════════════════════════════════════════════════════
//  ALIAS DE COMPATIBILIDAD RETROACTIVA (Para motores de la web)
// ════════════════════════════════════════════════════════════════
const LOTES = DESARROLLOS.filter(d => d.id >= 27);

// ════════════════════════════════════════════════════════════════
//  BLOG POSTS — imágenes locales de images/ciudades/
// ════════════════════════════════════════════════════════════════
const BLOG_POSTS = [
  {
    id: 1,
    slug: "merida-ciudad-mas-atractiva-inversion-2025",
    titulo: "Mérida: La Ciudad Más Atractiva para Inversión Inmobiliaria en 2025",
    ciudad: "Mérida",
    categoria: "Inversión",
    fecha: "2025-01-15",
    autor: "Equipo VEXO",
    tiempo_lectura: "6 min",
    imagen: "images/ciudades/CDMX-VEXO.jfif",
    resumen: "Mérida se posiciona como el mercado inmobiliario de mayor crecimiento en México, con plusvalías superiores al 15% anual en zonas como Temozón Norte y Cholul.",
    contenido: "<h2>¿Por qué invertir en Mérida?</h2><p>Mérida ha sido reconocida por múltiples organismos internacionales como una de las ciudades con mejor calidad de vida en América Latina. Su crecimiento poblacional sostenido, infraestructura de primer nivel y seguridad la convierten en el destino predilecto de inversionistas nacionales e internacionales.</p><h2>Zonas de mayor plusvalía</h2><p>Temozón Norte lidera con un crecimiento de +22% anual. Le siguen Cholul, Mérida Norte y Santa Gertrudis Copó como las zonas de mayor apreciación.</p><h2>Conclusión</h2><p>Invertir en Mérida en 2025 representa una oportunidad única de crecimiento patrimonial con alta demanda de renta.</p>",
  },
  {
    id: 2,
    slug: "cdmx-departamentos-preventa-mejor-inversion",
    titulo: "Departamentos en Preventa en CDMX: La Mejor Inversión del Año",
    ciudad: "Ciudad de México",
    categoria: "Preventa",
    fecha: "2025-02-10",
    autor: "Equipo VEXO",
    tiempo_lectura: "5 min",
    imagen: "images/ciudades/Polanco.vexo.jfif",
    resumen: "La Ciudad de México mantiene una demanda constante de vivienda premium. Colonias como Roma Norte, Narvarte y Condesa lideran el crecimiento.",
    contenido: "<h2>El mercado de preventa en CDMX</h2><p>Adquirir en preventa ofrece precios hasta un 30% menores al valor de mercado. Roma Norte, Narvarte y Polanco muestran los mejores indicadores de apreciación.</p><h2>¿Cómo elegir el mejor proyecto?</h2><p>Evalúa la ubicación, el desarrollador y las amenidades. VEXO ofrece proyectos con garantía de calidad y entrega en 2026.</p>",
  },
  {
    id: 3,
    slug: "guia-credito-hipotecario-mexico-2025",
    titulo: "Guía Completa: Cómo Obtener tu Crédito Hipotecario en México 2025",
    ciudad: "Mérida",
    categoria: "Financiamiento",
    fecha: "2025-03-05",
    autor: "Equipo VEXO",
    tiempo_lectura: "8 min",
    imagen: "images/ciudades/Vexo.Santa.Fe.jfif",
    resumen: "INFONAVIT, FOVISSSTE o crédito bancario: conoce las diferencias, requisitos y cuál es la mejor opción para tu situación.",
    contenido: "<h2>Tipos de crédito hipotecario</h2><p>En México existen tres principales opciones: INFONAVIT para trabajadores del sector privado, FOVISSSTE para empleados del gobierno, y crédito bancario tradicional para quienes no tienen acceso a los anteriores.</p><h2>¿Cuál es mejor para ti?</h2><p>INFONAVIT ofrece tasas preferenciales desde el 1.9% anual. FOVISSSTE desde el 4%. El bancario tiene mayor flexibilidad pero tasas del 9-12%. VEXO te asesora sin costo para elegir la mejor opción.</p>",
  },
  {
    id: 4,
    slug: "plusvalia-temozon-norte-merida-2025",
    titulo: "Temozón Norte: La Zona de Mayor Plusvalía en Mérida",
    ciudad: "Mérida",
    categoria: "Mercado",
    fecha: "2025-03-20",
    autor: "Equipo VEXO",
    tiempo_lectura: "5 min",
    imagen: "images/ciudades/CDMX-VEXO.jfif",
    resumen: "Temozón Norte se consolida como la zona de mayor apreciación inmobiliaria en Yucatán con un crecimiento del 22% anual.",
    contenido: "<h2>El boom de Temozón Norte</h2><p>Esta zona en el norte de Mérida concentrates los desarrollos más exclusivos de la ciudad. Su cercanía al aeropuerto, centros comerciales de primer nivel y colegios internacionales la convierten en la zona preferida por familias de alto poder adquisitivo.</p><h2>Proyección de inversión</h2><p>Un departamento adquirido en preventa por $2.5 MDP en Temozón Norte puede valer $3.8 MDP al momento de entrega. Una plusvalía del 52% en 18 meses.</p>",
  },
  {
    id: 5,
    slug: "invertir-playa-del-carmen-mayakoba-2025",
    titulo: "Invertir en Playa del Carmen: El Mercado Turístico que Nunca Para",
    ciudad: "Playa del Carmen",
    categoria: "Inversión",
    fecha: "2025-04-08",
    autor: "Equipo VEXO",
    tiempo_lectura: "6 min",
    imagen: "images/ciudades/Vexo.coyo.jfif",
    resumen: "El Caribe Mexicano sigue siendo uno de los destinos turísticos más visitados del mundo, generando alta demanda de renta vacacional.",
    contenido: "<h2>¿Por qué Playa del Carmen?</h2><p>Con más de 12 millones de turistas anuales, la Riviera Maya ofrece retornos en renta vacacional de hasta el 15% anual. Downtown Mayakoba es el proyecto más exclusivo del corredor.</p><h2>Ciudad Mayakoba</h2><p>Este desarrollo de uso mixto integra hotel, condominios, marina y playa privada. Una inversión segura en el destino turístico más importante de México.</p>",
  },
  {
    id: 6,
    slug: "roma-norte-barrio-trendy-inversion-cdmx",
    titulo: "Roma Norte: El Barrio Más Trendy para Invertir en CDMX",
    ciudad: "Ciudad de México",
    categoria: "Mercado",
    fecha: "2025-04-22",
    autor: "Equipo VEXO",
    tiempo_lectura: "5 min",
    imagen: "images/ciudades/Polanco.vexo.jfif",
    resumen: "Roma Norte fue nombrado el barrio más cool de América Latina por Time Out. Los departamentos aquí tienen la mayor demanda de renta en CDMX.",
    contenido: "<h2>El fenómeno Roma Norte</h2><p>Cafeterías de especialidad, galerías de arte, restaurantes de cocina de autor y bares de culto hacen de Roma Norte el epicentro cultural de CDMX. Los departamentos aquí son los más demandados en plataformas como Airbnb.</p><h2>Retorno de inversión</h2><p>El ROI en renta vacacional en Roma Norte supera el 12% anual. La demanda de profesionales y turistas mantiene alta la ocupación durante todo el año.</p>",
  },
  {
    id: 7,
    slug: "amenidades-que-mas-valoran-compradores-2025",
    titulo: "Las 10 Amenidades que Más Valoran los Compradores en 2025",
    ciudad: "Mérida",
    categoria: "Tendencias",
    fecha: "2025-05-10",
    autor: "Equipo VEXO",
    tiempo_lectura: "4 min",
    imagen: "images/ciudades/Vexo.Santa.Fe.jfif",
    resumen: "Rooftop, coworking, pet zone y gym son las amenidades más valoradas según nuestro estudio de mercado 2025.",
    contenido: "<h2>Las amenidades que hacen la diferencia</h2><p>Basados en 500 entrevistas con compradores de departamentos en Mérida y CDMX, identificamos las 10 amenidades más valoradas: 1. Rooftop / terraza social, 2. Gym equipado, 3. Coworking, 4. Alberca, 5. Pet zone, 6. BBQ, 7. Seguridad 24/7, 8. Lobby premium, 9. Espacios verdes, 10. Estacionamiento de bicicletas.</p>",
  },
  {
    id: 8,
    slug: "narvarte-colonias-emergentes-cdmx-inversion",
    titulo: "Narvarte y las Colonias Emergentes de CDMX: Dónde Invertir Ahora",
    ciudad: "Ciudad de México",
    categoria: "Mercado",
    fecha: "2025-05-28",
    autor: "Equipo VEXO",
    tiempo_lectura: "6 min",
    imagen: "images/ciudades/CDMX-VEXO.jfif",
    resumen: "Narvarte, Santa María la Ribera y Tabacalera se consolidan como los nuevos polos de inversión inmobiliaria en CDMX.",
    contenido: "<h2>Las colonias que están creciendo</h2><p>Narvarte Poniente y Oriente muestran un crecimiento del 18% anual. Santa María la Ribera, en proceso de gentrificación, ofrece los mejores precios de entrada. Tabacalera, frente al Monumento a la Revolución, se consolida como zona prime.</p><h2>¿Por qué invertir ahora?</h2><p>Los precios aún están por debajo de Roma Norte y Condesa, pero la tendencia es clara: en 5 años alcanzarán valores similares. Es la ventana de inversión perfecta.</p>",
  },
  {
    id: 9,
    slug: "polanco-santa-fe-lujo-cdmx-comparativa",
    titulo: "Polanco vs Santa Fe: ¿Cuál es la Mejor Zona de Lujo en CDMX?",
    ciudad: "Ciudad de México",
    categoria: "Comparativa",
    fecha: "2025-06-15",
    autor: "Equipo VEXO",
    tiempo_lectura: "7 min",
    imagen: "images/ciudades/Vexo.coyo.jfif",
    resumen: "Analizamos las dos zonas de mayor lujo en CDMX: Polanco con su oferta boutique y Santa Fe como hub corporativo.",
    contenido: "<h2>Polanco: El lujo boutique</h2><p>Polanco ofrece la mejor experiencia de vida urbana premium. Restaurantes Michelin, boutiques internacionales y los hoteles más exclusivos. Ideal para residencia o renta de largo plazo a ejecutivos y diplomáticos.</p><h2>Santa Fe: El hub corporativo</h2><p>Santa Fe concentra las sedes de más de 200 corporativos internacionales. Alta demanda de renta ejecutiva con contratos de 1-3 años. ROI estable del 8-10% anual. VEXO tiene presencia en ambas zonas con MAGNOLIA en Polanco y BLUM en Santa Fe.</p>",
  },
];

// ════════════════════════════════════════════════════════════════
//  CIUDADES
// ════════════════════════════════════════════════════════════════
const CIUDADES = [
  {
    id: "merida",
    nombre: "Mérida",
    eslogan: "La ciudad más segura y de mayor plusvalía en México",
    descripcion: "Mérida se ha consolidado como el destino inmobiliario preferido de México. Ciudad declarada varias veces como la más segura del país, con infraestructura de primer nivel, colegios internacionales, hospitales de especialidad y una calidad de vida excepcional. El crecimiento de zonas como Temozón Norte ha generado plusvalías superiores al 22% anual.",
    desarrollos_activos: 11,
    imagen_ciudad: "images/ciudades/Merida-Y-Vexo.webp",
    imagen_hero: "images/ciudades/CDMX-VEXO.jfif",
    inversion_corto: "En 12-18 meses puedes obtener una plusvalía del 15-25% sobre tu inversión inicial en preventa.",
    inversion_mediano: "A 3-5 años, los desarrollos en Temozón Norte proyectan un retorno total del 60-80% incluyendo renta.",
    inversion_largo: "A 10 años, propiedades en zonas premium de Mérida han triplicado su valor histórico.",
    stats: [
      { valor: "+22%", label: "Plusvalía anual Temozón Norte", icono: "trending_up" },
      { valor: "#1",   label: "Ciudad más segura de México",   icono: "shield"      },
      { valor: "11",   label: "Desarrollos VEXO activos",      icono: "apartment"   },
      { valor: "1.8M", label: "Turistas anuales",              icono: "flight"      },
    ],
    por_que_invertir: [
      "Ciudad más segura de México consecutivamente",
      "Plusvalía promedio del +22% anual en zonas premium",
      "Aeropuerto internacional con vuelos directos a EUA y Europa",
      "Infraestructura de talla mundial: hospitales, colegios, centros comerciales",
      "Alta demanda de renta por nómadas digitales y profesionales",
      "Clima y calidad de vida excepcionales",
    ],
    zonas: [
      { nombre: "Temozón Norte",       plusvalia: "22%", descripcion: "La zona de mayor crecimiento. Colegios, hospitales y acceso controlado." },
      { nombre: "Mérida Norte",        plusvalia: "18%", descripcion: "Expansión natural de la ciudad con infraestructura nueva." },
      { nombre: "Cholul",              plusvalia: "20%", descripcion: "Zona tranquila con alta demanda de familias." },
      { nombre: "Santa Gertrudis Copó",plusvalia: "16%", descripcion: "Fácil acceso a Periférico y zona norte." },
    ],
  },
  {
    id: "cdmx",
    nombre: "Ciudad de México",
    eslogan: "El corazón financiero y cultural de América Latina",
    descripcion: "Ciudad de México es el mercado inmobiliario más grande y dinámico de México. Con colonias icónicas como Roma Norte, Polanco, Condesa y Narvarte, la capital ofrece oportunidades de inversión uniques con alta demanda de renta por parte de ejecutivos, turistas y nómadas digitales.",
    desarrollos_activos: 14,
    imagen_ciudad: "images/ciudades/Polanco.vexo.jfif",
    imagen_hero: "images/ciudades/Polanco.vexo.jfif",
    inversion_corto: "En preventa, descuentos del 20-30% sobre el valor de mercado. Alta liquidez al momento de entrega.",
    inversion_mediano: "Roma Norte y Polanco proyectan un crecimiento del 12-18% anual sostenido en los próximos 5 años.",
    inversion_largo: "Históricamente, los departamentos en zonas prime de CDMX han duplicado su valor cada 8-10 años.",
    stats: [
      { valor: "9M+", label: "Habitantes en la zona metropolitana", icono: "location_city" },
      { valor: "#1",  label: "Barrio más trendy de LATAM (Roma Norte)", icono: "star" },
      { valor: "14",  label: "Desarrollos VEXO activos",               icono: "apartment" },
      { valor: "12%", label: "ROI renta vacacional promedio",           icono: "trending_up" },
    ],
    por_que_invertir: [
      "Mercado inmobiliario más líquido y grande de México",
      "Alta demanda de renta por ejecutivos, turistas y nómadas digitales",
      "Colonias de alta plusvalía: Roma Norte, Polanco, Condesa, Narvarte",
      "ROI en renta vacacional del 8-15% anual según zona",
      "Infraestructura de clase mundial: transporte, hospitales, universidades",
      "Destino turístico internacional con demanda constante",
    ],
    zonas: [
      { nombre: "Roma Norte",          plusvalia: "18%", descripcion: "El barrio más cool de LATAM. Máxima demanda de renta." },
      { nombre: "Polanco",             plusvalia: "15%", descripcion: "Zona de lujo boutique. Diplomáticos y ejecutivos." },
      { nombre: "Narvarte",            plusvalia: "16%", descripcion: "La zona emergente más demandada. Precios aún accesibles." },
      { nombre: "Condesa",             plusvalia: "14%", descripcion: "Art déco y naturaleza urbana. Alta demanda vacacional." },
    ],
  },
];

// ════════════════════════════════════════════════════════════════
//  EMPRESA
// ════════════════════════════════════════════════════════════════
const EMPRESA = {
  quienes_somos: "VEXO Real Estate es una empresa especializada en desarrollos residenciales premium en los mercados inmobiliarios más dinámicos de México: Mérida, Ciudad de México y Playa del Carmen. Nuestro enfoque es conectar a inversionistas con oportunidades reales de crecimiento patrimonial, ofreciendo asesoría personalizada y transparente en cada etapa del proceso.",
  mision: "Brindar asesoría inmobiliaria estratégica y confiable, ayudando a nuestros clientes a adquirir, vender o invertir en propiedades con claridad, seguridad y visión a largo plazo.",
  vision: "Ser una empresa líder en el sector inmobiliario en Mérida y Ciudad de México, reconocida por su transparencia, innovación y capacidad de generar valor en cada operación.",
  valores: [
    { nombre: "Transparencia", descripcion: "Información clara y honesta en cada etapa de la operación.", icono: "visibility" },
    { nombre: "Confianza",     descripcion: "Relaciones a largo plazo basadas en resultados comprobables.", icono: "handshake" },
    { nombre: "Innovación",    descripcion: "Tecnología y diseño al servicio de la inversión inmobiliaria.", icono: "lightbulb" },
    { nombre: "Excelencia",    descripcion: "Estándares de calidad premium en cada desarrollo.", icono: "star" },
    { nombre: "Compromiso",    descripcion: "Acompañamiento real desde el primer contacto hasta la escritura.", icono: "support_agent" },
  ],
  por_que_nosotros: [
    { titulo: "26+ desarrollos activos",          descripcion: "El portafolio más completo de Mérida, CDMX y Playa del Carmen." },
    { titulo: "Asesoría sin costo",               descripcion: "Te acompañamos en todo el proceso sin cobrar comisión adicional." },
    { titulo: "Financiamiento personalizado",     descripcion: "INFONAVIT, FOVISSSTE, bancario o recursos propios. Tú eliges." },
    { titulo: "Transparencia total",              descripcion: "Contratos claros, sin letra chica y con garantía de entrega." },
    { titulo: "Equipo especializado",             descripcion: "Asesores certificados con experiencia en mercados premium." },
  ],
  equipo: [
    { nombre: "Rosalia Robles",  cargo: "Directora General",   email: "rosalia.robles@vexorealestate.com",  foto: "images/equipo/rosalia.jpg" },
    { nombre: "Marco Flores",   cargo: "Director Comercial",  email: "marco.flores@vexorealestate.com",    foto: "images/equipo/marco.jpg"   },
    { nombre: "Equipo Mérida",  cargo: "Asesores Mérida",    email: "ventas@vexorealestate.com",           foto: "" },
    { nombre: "Equipo CDMX",    cargo: "Asesores CDMX",      email: "ventas@vexorealestate.com",           foto: "" },
  ],
  servicios: [
    { nombre: "Asesoría de inversión",  descripcion: "Analizamos tu perfil financiero y te recomendamos el mejor desarrollo según tus objetivos.", icono: "analytics" },
    { nombre: "Financiamiento",          descripcion: "Te orientamos en INFONAVIT, FOVISSSTE, crédito bancario o esquemas de pago directo.", icono: "account_balance" },
    { nombre: "Gestión de renta",        descripcion: "Administramos tu propiedad para maximizar el retorno en renta a corto y largo plazo.", icono: "home_work" },
    { nombre: "Acompañamiento legal",    descripcion: "Revisión de contratos y asesoría en el proceso de escrituración sin costo adicional.", icono: "gavel" },
    { nombre: "Valuación y plusvalía",   descripcion: "Reportes de mercado actualizados para tomar decisiones informadas de inversión.", icono: "trending_up" },
    { nombre: "Preventa exclusiva",      descripcion: "Acceso anticipado a proyectos VEXO con precios preferenciales antes del lanzamiento público.", icono: "key" },
  ],
  testimonios: [
    { nombre: "Carlos M.",    ciudad: "Mérida",          calificacion: 5, texto: "Compré en Alma Condos en preventa y ya tiene un 20% de plusvalía. El equipo VEXO me asesoró perfectamente en cada paso del proceso." },
    { nombre: "Ana L.",       ciudad: "Ciudad de México", calificacion: 5, texto: "Invertí en Basalto Narvarte y ha sido la mejor decisión financiera de mi vida. Renta en Airbnb con excelente ocupación." },
    { nombre: "Roberto G.",   ciudad: "Monterrey",        calificacion: 5, texto: "Compré en Mérida desde Monterrey sin problema. VEXO me guió en todo el proceso de forma remota y transparente." },
    { nombre: "Sofía R.",     ciudad: "Ciudad de México", calificacion: 5, texto: "Excelente asesoría para obtener mi crédito INFONAVIT. Pensé que era complicado y VEXO hizo todo muy sencillo." },
    { nombre: "Familia Torres", ciudad: "Mérida",         calificacion: 5, texto: "Compramos Nuan Temozón para vivir y es exactamente lo que buscábamos. Zona segura, amenidades y excelente ubicación." },
    { nombre: "Diego P.",     ciudad: "CDMX",             calificacion: 5, texto: "Lirio Reforma superó todas mis expectativas. El rooftop con vista al Ángel es simplemente espectacular." },
  ],
  stats: [
    { valor: "26+",  label: "Desarrollos activos",         icono: "apartment"     },
    { valor: "2",    label: "Ciudades estratégicas",        icono: "location_city" },
    { valor: "500+", label: "Clientes satisfechos",         icono: "people"        },
    { valor: "+22%", label: "Plusvalía promedio anual",     icono: "trending_up"   },
  ],
};

// ════════════════════════════════════════════════════════════════
//  DESCARGAS
// ════════════════════════════════════════════════════════════════
const DESCARGAS = {
  brochures: DESARROLLOS
    .filter(function(d) { return d.brochure && d.brochure.length > 0; })
    .map(function(d) {
      return {
        desarrollo_id: d.id,
        titulo: d.nombre,
        descripcion: d.zona + " · " + d.ciudad,
        ciudad: d.ciudad,
        archivo: d.brochure,
      };
    }),
  guias: [
    { titulo: "Guía: Cómo invertir en preventa",    descripcion: "Todo lo que necesitas antes de comprar.", archivo: "" },
    { titulo: "Reporte de mercado Mérida 2025",      descripcion: "Análisis de plusvalía por zonas.",        archivo: "" },
    { titulo: "Guía de financiamiento hipotecario",  descripcion: "INFONAVIT, FOVISSSTE y bancario.",        archivo: "" },
    { titulo: "Checklist del comprador VEXO",        descripcion: "Pasos para tu primera inversión.",        archivo: "" },
  ],
};

// ════════════════════════════════════════════════════════════════
//  LEGAL
// ════════════════════════════════════════════════════════════════
const LEGAL = {
  privacidad: {
    titulo: "Política de Privacidad",
    fecha: "enero 2025",
    secciones: [
      { seccion: "1. Responsable del tratamiento", texto: "VEXO REAL ESTATE, con domicilio en Iturbide 32, Centro, Cuauhtémoc, Ciudad de México, es el responsable del tratamiento de sus datos personales." },
      { seccion: "2. Datos que recabamos", texto: "Nombre completo, correo electrónico, teléfono, interés inmobiliario y cualquier dato que usted nos proporcione voluntariamente a través de nuestros formularios de contacto." },
      { seccion: "3. Finalidades del tratamiento", texto: "Sus datos se utilizan para: (a) atender sus solicitudes de información, (b) enviarle información sobre desarrollos de su interés, (c) agendar citas y visitas, (d) dar seguimiento a su proceso de compra." },
      { seccion: "4. Transferencia de datos", texto: "VEXO no comparte, vende ni transfiere sus datos personales a terceros sin su consentimiento previo, salvo obligación legal." },
      { seccion: "5. Derechos ARCO", texto: "Usted tiene derecho a Acceder, Rectificar, Cancelar u Oponerse al tratamiento de sus datos. Envíe su solicitud a: ayuda@vexorealestate.com" },
      { seccion: "6. Cambios a esta política", texto: "Nos reservamos el derecho de modificar esta política en cualquier momento. Los cambios serán publicados en nuestro sitio web." },
    ],
  },
  terminos: {
    titulo: "Términos y Condiciones",
    fecha: "enero 2025",
    secciones: [
      { seccion: "1. Aceptación", texto: "Al utilizar este sitio web, usted acepta los presentes términos y condiciones en su totalidad. Si no está de acuerdo, por favor deje de utilizar el sitio." },
      { seccion: "2. Información del sitio", texto: "La información contenida en este sitio es de carácter informativo. Los precios, disponibilidad y características de los desarrollos pueden cambiar sin previo aviso." },
      { seccion: "3. Propiedad intelectual", texto: "Todo el contenido de este sitio, incluyendo textos, imágenes y logotipos, es propiedad de VEXO Real Estate y está protegido por las leyes de propiedad intelectual." },
      { seccion: "4. Limitación de responsabilidad", texto: "VEXO no garantiza la exactitud absoluta de la información publicada y no se hace responsable de decisiones tomadas con base en la misma sin asesoría directa." },
      { seccion: "5. Jurisdicción", texto: "Cualquier controversia se resolverá de conformidad con las leyes de los Estados Unidos Mexicanos, en los tribunales de la Ciudad de México." },
    ],
  },
  aviso_legal: {
    titulo: "Aviso Legal",
    fecha: "enero 2025",
    secciones: [
      { seccion: "Identidad del responsable", texto: "VEXO REAL ESTATE · Iturbide 32, Centro, Cuauhtémoc, CDMX · ventas@vexorealestate.com · +52 55 2708 1749" },
      { seccion: "Objeto del sitio", texto: "Este sitio web tiene como finalidad presentar el portafolio de desarrollos inmobiliarios de VEXO Real Estate y facilitar el contacto con asesores especializados." },
      { seccion: "Exención de responsabilidad", texto: "VEXO no se responsabiliza por el uso indebido de la información contenida en este sitio ni por los daños derivados de su utilización." },
    ],
  },
};

// ════════════════════════════════════════════════════════════════
//  HELPERS — funciones globales de acceso a datos
// ════════════════════════════════════════════════════════════════
function getImgPrincipal(d) {
  function _n(s) {
    if (!s || s.length < 5) return "";
    if (s.indexOf("VEXO_WEB/Desarrollos/") === 0)
      return s.replace("VEXO_WEB/Desarrollos/", "images/Desarrollos/");
    return s;
  }
  var p = _n(d.foto_principal_url);
  if (p) return p;
  if (Array.isArray(d.imagenes) && d.imagenes.length > 0) {
    var p2 = _n(d.imagenes[0]);
    if (p2) return p2;
  }
  return d.imagen_fallback || "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80";
}

function getDesarrolloBySlug(s) {
  return DESARROLLOS.filter(function(d) {
    return d.slug === s || d.url_slug === s;
  })[0] || null;
}

function getDesarrolloById(id) {
  return DESARROLLOS.filter(function(d) {
    return String(d.id) === String(id);
  })[0] || null;
}

function getDescargas(tipo) {
  return tipo === "brochures" ? DESCARGAS.brochures : DESCARGAS.guias;
}

// ════════════════════════════════════════════════════════════════
//  EXPORTS GLOBALES
// ════════════════════════════════════════════════════════════════
window.CONFIG             = CONFIG;
window.DESARROLLOS        = DESARROLLOS;
window.PROPIEDADES        = DESARROLLOS; 
window.BLOG_POSTS         = BLOG_POSTS;
window.CIUDADES           = CIUDADES;
window.EMPRESA            = EMPRESA;
window.DESCARGAS          = DESCARGAS;
window.LEGAL              = LEGAL;
window.getImgPrincipal    = getImgPrincipal;
window.getDesarrolloBySlug = getDesarrolloBySlug;
window.getDesarrolloById  = getDesarrolloById;
window.getDescargas       = getDescargas;
window.LOTES              = LOTES; 
window.VEXO_DATA_VERSION  = "2026-05-MASTER";
window.VEXO_TOTAL_DESARROLLOS = DESARROLLOS.filter(d => d.id < 27).length;
window.VEXO_TOTAL_LOTES = LOTES.length;